config_target: src.models.model_configs.metricVAEConfig

wandb:
  project: sweep10
  
ddconfig:
  name: "Swin-Tiny" #"Efficient-B0-RA"
  input_dim: [1, 288, 128]
  dec_use_local_attn: False # Currently a bug in this somewhere
  latent_dim: 128
#  n_conv_layers: 5

lossconfig:
  reconstruction_loss: "L2"

  # KLD
  kld_weight: 1.0
  schedule_kld: True
  
  # Metric
  schedule_metric: True
  metric_weight: 1.0
  temperature: 0.1
  margin: 1.0
  

  # PIPS
  schedule_pips: True
  pips_flag: True
  pips_weight: 7.5
  pips_net: "vgg"

  # GAN
  schedule_gan: True
  use_gan: True
  gan_weight: 1.0
  gan_net: "patch4scale"
  lambda_feat_match: 10.0
  

dataconfig:
  target: "BasicDataset"
  num_workers: 8
  batch_size: 256
  wrap: True
  root: ${ancestor:${hydra:run.dir},2} #"/media/nick/hdd021/Cole Trapnell's Lab Dropbox/Nick Lammers/Nick/morphseq/training_data/20241107_ds/"

trainconfig:
  benchmark: True
  accumulate_grad_batches: 1
  max_epochs: 50
  save_epochs: [9, 19, 29]
  eval_gpu_flag: True